### ISSUE TITLE
android support?

### ISSUE THREAD

**Issue by chentc** [agent8/sift-java-sdk#1]
Hi folks, 

I am trying to use the java sdk in Android by importing the library like the following:
` compile 'com.easilydo:sift-sdk:1.0.0'`
But I found the sdk requires unirest library, which is not built for android network operations. 

Any plans to release an android sdk? Thanks!

**Comment by cstritter** [comment]
I think you might be able to accomplish this with Unirest. 
Unirest allows you to set the HttpClient that you want it to use (http://javadox.com/com.mashape.unirest/unirest-java/1.3.11/com/mashape/unirest/http/Unirest.html#setHttpClient(org.apache.http.client.HttpClient)).

This is the same org.apache interface that is used by android (https://developer.android.com/reference/org/apache/http/client/HttpClient.html).

**Comment by chentc** [comment]
I've set up the client secrets and oauth, but when I try to get parsed results,            
HttpResponse<String> response = request.asString();

It generates the following error. It appears to be something wrong going on in one of the library imports.

`                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                               at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:761)
                                                                            Caused by: java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/message/BasicLineFormatter; in class Lorg/apache/http/message/BasicLineFormatter; or its superclasses (declaration of 'org.apache.http.message.BasicLineFormatter' appears in /system/framework/org.apache.http.legacy.boot.jar)
                                                                               at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
                                                                               at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
                                                                               at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
                                                                               at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:66)
                                                                               at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:78)
                                                                               at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:57)
                                                                               at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:499)
                                                                               at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
                                                                               at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
                                                                               at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
                                                                               at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:105)
                                                                               at com.mashape.unirest.http.options.Options.refresh(Options.java:72)
                                                                               at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
                                                                               at com.mashape.unirest.http.options.Options.getOption(Options.java:42)
                                                                               at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
                                                                               at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
                                                                               at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
                                                                               at com.github.privacystreams.communication.BaseGmailProvider.executeRequest(BaseGmailProvider.java:73)
                                                                               at com.github.privacystreams.communication.BaseGmailProvider.discovery(BaseGmailProvider.java:118)
                                                                               at com.github.privacystreams.communication.BaseGmailProvider.getMessageDetails(BaseGmailProvider.java:217)
                                                                               at com.github.privacystreams.communication.BaseGmailProvider.getDataFromApi(BaseGmailProvider.java:271)
                                                                               at com.github.privacystreams.communication.BaseGmailProvider.access$000(BaseGmailProvider.java:55)
                                                                               at com.github.privacystreams.communication.BaseGmailProvider$FetchEmailTask.doInBackground(BaseGmailProvider.java:345)
                                                                               at com.github.privacystreams.communication.BaseGmailProvider$FetchEmailTask.doInBackground(BaseGmailProvider.java:335)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                               at java.lang.Thread.run(Thread.java:761) 
06-12 18:53:31.384 25756-25766/com.github.privacystreams E/System: Uncaught exception thrown by finalizer
06-12 18:53:31.385 25756-25766/com.github.privacystreams E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.atomic.AtomicBoolean.compareAndSet(boolean, boolean)' on a null object reference
                                                                       at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.shutdown(PoolingHttpClientConnectionManager.java:349)
                                                                       at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.finalize(PoolingHttpClientConnectionManager.java:172)
                                                                       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                       at java.lang.Thread.run(Thread.java:761)

`
